name: iot_pulse
description: "iot_pulse project."
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^12.0.1
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  google_fonts: ^6.3.3
  font_awesome_flutter: ^10.12.0
  animate_do: ^4.2.0
  sleek_circular_slider: ^2.1.0
  flutter_reactive_ble: ^5.4.0
  shared_preferences: ^2.5.4
  go_router: ^17.0.1
  provider: ^6.1.5+1
  intl: ^0.20.2
  printing: ^5.14.2
  pdf: ^3.11.3
  internet_connection_checker: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/icon/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#673AB7"
  adaptive_icon_foreground: "assets/icon/app_icon.png"